---
title: "Changelog"
author: "Asmita Roy"
date: "`r Sys.Date()`"
output: html_document
---

# Changelog
All notable changes to this project will be documented in this file. Changes are categorized as Added, Changed, Deprecated, Removed, Fixed, and Security.
## -2026-06-13
### Changed
-stats.R: Added a function that calculates area under curve for Kcross.
-pval_v3.R: Added code to compute pvalue for auc as well as median r value Kcross. Null generation has been done by toroidal shift, minus correction, variance correction
### Fixed
-pval_v3.R: Bug - lambda was named the same for original data as well as for null data, leading to incorrect p values. This has been fixed by renaming the lambda1 and lambda2 for original data to n1 and n2.

## -2026-06-01
### Added
-pval_v3.R: Trying a new type of null generation called EVC - expectation variance correction but that is doing poorly.

## -2026-05-07
### exploratory_sd.R: Added code to check the behavior of standard deviation versus sample sizes and shift vectors for the K statistics.

## -2026-04-28
### Added
- pval_v2.R: Added a new function pval.assoc that computes pval for Kcross, Kstar and NN for torshift, RS_ker for different kernels and different bandwidths. 
- sims.R: Added code to run simulations for the new pval.assoc function.
- Power_realdata.R: 10 percent of the points of a real slide is sampled, power is computed for all methods using pval.assoc function.

### Changed
- var_corr.R: Tried variance correction with the weights determined by sample sizes of the restricted window. Has no size inflation, possibly doing a tiny bit better than weights determined by the translation vector, but have not compared the two directly.

## -2026-04-15
### Deprecated
- var_corr.R: Deprecated the original variance correction code that was used for the presentation on April 2, as it did not perform well in terms of size. Will explore other methods for variance correction.

### Changed
- stats.R: compute_K now has K, Kstar and Kcor only for border correction. 
### Added
- stats.R: an NN function is added.

## -2026-04-13
### Added 
- var_corr.R: tried some ways to improve size for variance correction

## -2026-04-09
### Added
- sims.R: simulations for square window
- sims_irregW.R: simulations for irregular window

## -2026-04-03
### Added
-pval.R: Added extra code to compute all 9 stats using M3 - variance correction
### Security
- pval.R: Added redundancies so code doesn't fail when intersection window does not have any points of shift taxa or base.taxa.

## - 2026-04-02
### Added
- compute_K.R: Added a new function `compute_K()` to compute various K statistics for spatial point patterns, including border isotropic and translation corrections.
- pval.R: Added a function pval_assoc that computes p values for all 9 stats returned by compute K() using M1 and M2
- sims.R: Added a new script `sims.R` to perform simulations for evaluating the performance of the K statistics under different scenarios. Calls generate_data.R, compute_K.R, and pval.R

## - 2026-04-02
### Added
- generate_data.R: Added a new function `generate_data()` to create synthetic datasets for testing purposes.
- variance_correction_codes.R: Downloaded the variance correction code from internet and added it to the project for future use.
- RK_torshift_bothsided.R: Imported the RK toroidal shift code that was used to generate results for presentation on April 2
- read_ruoqian's_data: Imported from last version, reads the real data and plots it. 